name: Node.js Tagging Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get version from tag
      id: get-version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Validate semver format
      run: |
        if [[ ! "${{ steps.get-version.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Must be in format x.y.z"
          exit 1
        fi
  
  update-changelog:
    needs: validate-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update CHANGELOG.md
      run: |
        if [ ! -f CHANGELOG.md ]; then
          echo "# Changelog\n\nAll notable changes to this project will be documented in this file.\n" > CHANGELOG.md
        fi
        
        VERSION="${{ needs.validate-tag.outputs.version }}"
        DATE=$(date +"%Y-%m-%d")
        
        sed -i "4i\\n## [${VERSION}] - ${DATE}\n\n${{ steps.changelog.outputs.changelog }}\n" CHANGELOG.md
    
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update changelog for v${{ needs.validate-tag.outputs.version }}"
        file_pattern: CHANGELOG.md
  
  update-package-json:
    needs: validate-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Update package.json version
      run: |
        VERSION="${{ needs.validate-tag.outputs.version }}"
        npm version $VERSION --no-git-tag-version
    
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: bump version to v${{ needs.validate-tag.outputs.version }}"
        file_pattern: package.json package-lock.json
  
  create-github-release:
    needs: [validate-tag, update-changelog, update-package-json]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Changes in this Release
          
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  notify:
    needs: create-github-release
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        text: 'New version v${{ needs.validate-tag.outputs.version }} has been tagged and released! 🎉'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}