# Example Prometheus Configuration (prometheus.yml)

global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s # Default evaluation interval

# Alertmanager configuration (if used)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   - "/etc/prometheus/rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  # Example job for scraping a Node Exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node-exporter-hostname:9100']

  # Example job for scraping an application exposing metrics
  # - job_name: 'my_application'
  #   static_configs:
  #     - targets: ['app-hostname:8080']